### ISSUE TITLE
Unable to install dashboard on a mos 9.2 environment

### ISSUE THREAD

**Issue by pack72** [b3lab/safir_monitor_dashboard#2]
Hi,
I receive the following error when trying to install the dashboard on a MIrantis mos 9.2 openstack deployment based on Mitaka,

ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pbr/core.py", line 109, in pbr
    attrs = util.cfg_to_args(path)
  File "/usr/lib/python2.7/dist-packages/pbr/util.py", line 243, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/usr/lib/python2.7/dist-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/usr/lib/python2.7/dist-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/usr/lib/python2.7/dist-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/usr/lib/python2.7/dist-packages/pbr/packaging.py", line 668, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
error in setup command: Error parsing /root/safir_monitor_dashboard-ceilometer_backend/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?

All hosts are running ubuntu 14.04.5 LTS with python 2.7.6

root@node-208:~/safir_monitor_dashboard-ceilometer_backend# pip freeze |grep pbr
pbr==1.8.0

Please help

**Comment by esracelik** [comment]
Hi,

Can you run the following line before installation and try again?

 export PBR_VERSION=1.0

**Comment by pack72** [comment]
Thanks so much, the install now works but ./manage.py collectstatic command does not seem to copy the templates to the correct locations,

root@node-208:/usr/share/openstack-dashboard# ./manage.py collectstatic
WARNING:root:"dashboards" and "default_dashboard" in (local_)settings is DEPRECATED now and may be unsupported in some future release. The preferred way to specify the order of dashboards and the default dashboard is the pluggable dashboard mechanism (in /usr/share/openstack-dashboard/openstack_dashboard/enabled, /usr/share/openstack-dashboard/openstack_dashboard/local/enabled).

You have requested to collect static files at the destination
location as specified in your settings:

    /usr/share/openstack-dashboard/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes

0 static files copied to '/usr/share/openstack-dashboard/static', 2171 unmodified.

I get the below error in Horizon,

2017-10-23 09:02:38,854 7491 ERROR django.request Internal Server Error: /horizon/admin/hypervisor_monitor/
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/usr/lib/python2.7/dist-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/usr/lib/python2.7/dist-packages/django/template/response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/lib/python2.7/dist-packages/django/template/response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/lib/python2.7/dist-packages/django/template/response.py", line 78, in resolve_template
    return loader.select_template(template, using=self.using)
  File "/usr/lib/python2.7/dist-packages/django/template/loader.py", line 76, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list))
TemplateDoesNotExist: admin/hypervisor_monitor/index.html

How can i copy the necessary files manually?

**Comment by esracelik** [comment]
Did you copy the files in monitor_dashboard/enabled to /usr/share/openstack-dashboard/openstack_dashboard/local/enabled/ ?

**Comment by pack72** [comment]
yes, i did, i am going to redo the install from scratch again just to make sure i haven't missed anything.

**Comment by pack72** [comment]
ok, i have done a re-install from scratch and copied the files over as per the README.rst but the above error still persists.  

./manage.py collectstatic does not ad any static files

**Comment by esracelik** [comment]
ok, can you verify that dashboard can actually collect static files? you can temporarily rename a file 

$ mv /usr/share/openstack-dashboard/static/dashboard/admin/admin.module.spec.js /usr/share/openstack-dashboard/static/dashboard/admin/admin.module.spec.jsDEF
$ /usr/share/openstack-dashboard/manage.py collectstatic

**Comment by pack72** [comment]
Hi, yes, static collection does seem to be working,
root@node-208:~# /usr/share/openstack-dashboard/manage.py collectstatic
WARNING:root:"dashboards" and "default_dashboard" in (local_)settings is DEPRECATED now and may be unsupported in some future release. The preferred way to specify the order of dashboards and the default dashboard is the pluggable dashboard mechanism (in /usr/share/openstack-dashboard/openstack_dashboard/enabled, /usr/share/openstack-dashboard/openstack_dashboard/local/enabled).

You have requested to collect static files at the destination
location as specified in your settings:

    /usr/share/openstack-dashboard/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Copying '/usr/share/openstack-dashboard/openstack_dashboard/dashboards/admin/static/dashboard/admin/admin.module.spec.js'

1 static file copied to '/usr/share/openstack-dashboard/static', 2170 unmodified.

What what i can see the index.html files Horizon is looking for do not actually exist in the folders.

**Comment by esracelik** [comment]
OK I could reproduce this error at last.. It happens when you use the release archive to install the monitor dashboard. I will be trying to solve the problem with the release archives, meanwhile can you re-install the monitor dashboard from the repository, I think this will solve your problem

$ git clone https://github.com/b3lab/safir_monitor_dashboard.git -b ceilometer_backend
$ cd safir_monitor_dashboard
$ sudo pip install .

**Comment by pack72** [comment]
Thanks, the install works fine now and the panels are sucessfully added to to Horizon

The compute monitor panel unfortunately does not display correctly though,
![image](https://user-images.githubusercontent.com/17250458/31983867-7f8eeffa-b95f-11e7-9ca3-984038525f5a.png)

Please advise

**Comment by esracelik** [comment]
Can you send the error message?
You can see it with inspect option at the browser

**Comment by pack72** [comment]
Not sure if this helps,

GET https://m2lab.m2cloud.co.za/horizon/static/dashboard/css/00eaa7a7a4c8.css [HTTP/1.1 200 OK 0ms]
GET https://m2lab.m2cloud.co.za/horizon/project/monitor [HTTP/1.1 301 MOVED PERMANENTLY 4556ms]
GET https://m2lab.m2cloud.co.za/horizon/project/monitor/ [HTTP/1.1 200 OK 1346ms]
GET https://m2lab.m2cloud.co.za/horizon/static/dashboard/css/34f8a8f8d5e5.css [HTTP/1.1 200 OK 368ms]
GET https://m2lab.m2cloud.co.za/horizon/static/dashboard/css/00eaa7a7a4c8.css [HTTP/1.1 200 OK 1823ms]
GET https://m2lab.m2cloud.co.za/horizon/static/css/nv.d3.css [HTTP/1.1 200 OK 366ms]
GET https://m2lab.m2cloud.co.za/horizon/static/css/_usages.css [HTTP/1.1 200 OK 459ms]
GET https://m2lab.m2cloud.co.za/horizon/static/dashboard/js/c022185eb028.js [HTTP/1.1 200 OK 1719ms]
GET https://m2lab.m2cloud.co.za/horizon/static/js/angular.js [HTTP/1.1 200 OK 1903ms]
GET https://m2lab.m2cloud.co.za/horizon/static/js/angular-nvd3.js [HTTP/1.1 200 OK 1475ms]
GET https://m2lab.m2cloud.co.za/horizon/static/js/d3.js [HTTP/1.1 200 OK 3541ms]
GET https://m2lab.m2cloud.co.za/horizon/static/js/nv.d3.js [HTTP/1.1 200 OK 2381ms]
GET https://m2lab.m2cloud.co.za/horizon/i18n/js/horizon+openstack_dashboard+monitor_dashboard/ [HTTP/1.1 200 OK 1942ms]
GET https://m2lab.m2cloud.co.za/horizon/static/dashboard/js/82a64c3c0998.js [HTTP/1.1 200 OK 5008ms]
Unknown property ‘user-select’.  Declaration dropped.  34f8a8f8d5e5.css:97:13
Unknown property ‘-moz-box-shadow’.  Declaration dropped.  34f8a8f8d5e5.css:775:17
Unknown property ‘-moz-background-clip’.  Declaration dropped.  34f8a8f8d5e5.css:778:22
Expected declaration but found ‘*’.  Skipped to next declaration.  34f8a8f8d5e5.css:780:2
Expected declaration but found ‘*’.  Skipped to next declaration.  34f8a8f8d5e5.css:781:2
Error in parsing value for ‘shape-rendering’.  Declaration dropped.  34f8a8f8d5e5.css:1019:18
Unknown property ‘user-select’.  Declaration dropped.  nv.d3.css:259:23
Unknown property ‘user-select’.  Declaration dropped.  nv.d3.css:537:23
Expected declaration but found ‘@include’.  Skipped to next declaration.  _usages.css:12:2
Expected declaration but found ‘@extend’.  Skipped to next declaration.  _usages.css:16:2
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector.  00eaa7a7a4c8.css:27:17
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped.  00eaa7a7a4c8.css:55:28
Unknown pseudo-class or pseudo-element ‘-webkit-inner-spin-button’.  Ruleset ignored due to bad selector.  00eaa7a7a4c8.css:163:84
Unknown pseudo-class or pseudo-element ‘-webkit-search-cancel-button’.  Ruleset ignored due to bad selector.  00eaa7a7a4c8.css:173:88
Unknown property ‘orphans’.  Declaration dropped.  00eaa7a7a4c8.css:222:29
Unknown property ‘widows’.  Declaration dropped.  00eaa7a7a4c8.css:223:28
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped.  00eaa7a7a4c8.css:258:27
Expected color but found ‘auto’.  Expected color but found ‘-webkit-focus-ring-color’.  Expected end of value but found ‘-webkit-focus-ring-color’.  Error in parsing value for ‘outline’.  Declaration dropped.  00eaa7a7a4c8.css:893:29
Expected end of value but found ‘\9 ’.  Error in parsing value for ‘width’.  Declaration dropped.  00eaa7a7a4c8.css:904:18
Expected end of value but found ‘\9 ’.  Error in parsing value for ‘width’.  Declaration dropped.  00eaa7a7a4c8.css:921:22
Expected end of value but found ‘\9 ’.  Error in parsing value for ‘margin-top’.  Declaration dropped.  00eaa7a7a4c8.css:1998:26
Expected color but found ‘auto’.  Expected color but found ‘-webkit-focus-ring-color’.  Expected end of value but found ‘-webkit-focus-ring-color’.  Error in parsing value for ‘outline’.  Declaration dropped.  00eaa7a7a4c8.css:2013:31
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector.  00eaa7a7a4c8.css:2048:40
Unknown pseudo-class or pseudo-element ‘-webkit-input-placeholder’.  Ruleset ignored due to bad selector.  00eaa7a7a4c8.css:2050:43
Expected end of value but found ‘�’.  Error in parsing value for ‘line-height’.  Declaration dropped.  00eaa7a7a4c8.css:2069:27
Expected end of value but found ‘\9 ’.  Error in parsing value for ‘margin-top’.  Declaration dropped.  00eaa7a7a4c8.css:2160:18
Unknown property ‘user-select’.  Declaration dropped.  00eaa7a7a4c8.css:2527:13
Expected color but found ‘auto’.  Expected color but found ‘-webkit-focus-ring-color’.  Expected end of value but found ‘-webkit-focus-ring-color’.  Error in parsing value for ‘outline’.  Declaration dropped.  00eaa7a7a4c8.css:2530:17
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:2544:16
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:2838:10
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:3043:10
Expected end of value but found ‘\9 ’.  Error in parsing value for ‘width’.  Declaration dropped.  00eaa7a7a4c8.css:3898:16
Error in parsing value for ‘background-image’.  Declaration dropped.  00eaa7a7a4c8.css:4019:24
Error in parsing value for ‘background-image’.  Declaration dropped.  00eaa7a7a4c8.css:4055:22
Error in parsing value for ‘background-image’.  Declaration dropped.  00eaa7a7a4c8.css:4068:22
Error in parsing value for ‘background-image’.  Declaration dropped.  00eaa7a7a4c8.css:4081:22
Error in parsing value for ‘background-image’.  Declaration dropped.  00eaa7a7a4c8.css:4094:22
Unknown property ‘zoom’.  Declaration dropped.  00eaa7a7a4c8.css:4102:6
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:4572:10
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:4583:12
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:4648:18
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:4651:20
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:4719:10
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:4722:12
Expected end of value but found ‘\9 ’.  Error in parsing value for ‘width’.  Declaration dropped.  00eaa7a7a4c8.css:4917:20
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:4947:10
Error in parsing value for ‘background-image’.  Declaration dropped.  00eaa7a7a4c8.css:4954:22
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:4957:12
Error in parsing value for ‘background-image’.  Declaration dropped.  00eaa7a7a4c8.css:4963:24
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:4966:14
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:4973:16
Expected end of value but found ‘\9 ’.  Error in parsing value for ‘background-color’.  Declaration dropped.  00eaa7a7a4c8.css:5016:27
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped.  00eaa7a7a4c8.css:5289:25
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:5366:10
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:5372:12
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:5378:14
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:5384:16
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:5390:18
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped.  00eaa7a7a4c8.css:7181:29
Expected declaration but found ‘*’.  Skipped to next declaration.  00eaa7a7a4c8.css:7234:4
Expected declaration but found ‘*’.  Skipped to next declaration.  00eaa7a7a4c8.css:7321:10
Expected declaration but found ‘*’.  Skipped to next declaration.  00eaa7a7a4c8.css:7345:8
Expected declaration but found ‘*’.  Skipped to next declaration.  00eaa7a7a4c8.css:7369:8
Error in parsing value for ‘cursor’.  Declaration dropped.  00eaa7a7a4c8.css:7666:10
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:8359:14
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped.  00eaa7a7a4c8.css:8427:29
Error in parsing value for ‘background-image’.  Declaration dropped.  00eaa7a7a4c8.css:8960:22
Error in parsing value for ‘background-image’.  Declaration dropped.  00eaa7a7a4c8.css:8963:22
Expected color but found ‘top’.  Error in parsing value for ‘background-image’.  Declaration dropped.  00eaa7a7a4c8.css:8964:38
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:8966:12
Error in parsing value for ‘background-image’.  Declaration dropped.  00eaa7a7a4c8.css:8972:24
Error in parsing value for ‘background-image’.  Declaration dropped.  00eaa7a7a4c8.css:8975:24
Expected color but found ‘top’.  Error in parsing value for ‘background-image’.  Declaration dropped.  00eaa7a7a4c8.css:8976:40
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:8978:14
Error in parsing value for ‘background-image’.  Declaration dropped.  00eaa7a7a4c8.css:8984:26
Error in parsing value for ‘background-image’.  Declaration dropped.  00eaa7a7a4c8.css:8987:26
Expected color but found ‘top’.  Error in parsing value for ‘background-image’.  Declaration dropped.  00eaa7a7a4c8.css:8988:42
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  00eaa7a7a4c8.css:8990:16
GET https://m2lab.m2cloud.co.za/horizon/static/themes/vendor/img/logo.png [HTTP/1.1 304 Not Modified 193ms]
GET https://m2lab.m2cloud.co.za/horizon/static//themes/vendor//img/horizon-universe.jpg [HTTP/1.1 304 Not Modified 397ms]
GET XHR https://m2lab.m2cloud.co.za/horizon/static/framework/widgets/toast/toast.html [HTTP/1.1 200 OK 418ms]
GET XHR https://m2lab.m2cloud.co.za/horizon/static/dashboard/project/monitor/samples/monitor.html [HTTP/1.1 200 OK 372ms]
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  c022185eb028.js:350:155
GET https://m2lab.m2cloud.co.za/horizon/static/dashboard/css/00eaa7a7a4c8.css [HTTP/1.1 200 OK 0ms]
Error in parsing value for ‘background’.  Declaration dropped.  monitor
GET XHR https://m2lab.m2cloud.co.za/horizon/static/framework/widgets/headers/hz-page-header.html [HTTP/1.1 200 OK 0ms]
GET XHR https://m2lab.m2cloud.co.za/horizon/static/framework/widgets/table/hz-table-footer.html [HTTP/1.1 200 OK 0ms]

**Comment by esracelik** [comment]
I can only see the following line complaining about monitor dashboard but it does not make sense to me
"Error in parsing value for ‘background’. Declaration dropped. monitor"

Maybe it is an issue about Mirantis OpenStack Dashboard, did you ever try to plug another panel to it? 
I will also try Mirantis OpenStack but their content site is not reachable at the moment.

Can you send if you see any other log messages related to monitor dashboard from server side or client side?

**Comment by pack72** [comment]
I have successfully added this panel, https://github.com/simonpasquier/horizon-telemetry-dashboard but the metrics display is not that use friendly hence i am looking at others.

**Comment by esracelik** [comment]
OK, our dashboard shows metric charts like the following, maybe you can try in a devstack environment

![image](https://user-images.githubusercontent.com/14159766/32050874-237a7994-ba5b-11e7-9d17-026b9713a12a.png)

**Comment by pack72** [comment]
Hi,

This is what my panel renders as,

![image](https://user-images.githubusercontent.com/17250458/42909961-112b9b18-8ae6-11e8-8bd9-f3fa16d42c7e.png)
